[package]
name = "short"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
urlshortener = "3.0.0"
cli-clipboard = "0.2.1"
clap = { version = "3.1.12", features = ["derive"] }
